//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reto.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Alumno
    {
        public Alumno()
        {
            this.Alumno_Juego = new HashSet<Alumno_Juego>();
            this.Matricula = new HashSet<Matricula>();
        }
    
        [Key]
        public int IdAlumno { get; set; }
        public Nullable<int> IdPersona { get; set; }
    
        public virtual ICollection<Alumno_Juego> Alumno_Juego { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Matricula> Matricula { get; set; }
    }
}
