//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reto.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Juego
    {
        public Juego()
        {
            this.Alumno_Juego = new HashSet<Alumno_Juego>();
        }

        [Key]
        public int IdJuego { get; set; }
        public Nullable<int> Reto { get; set; }
        public string Nivel { get; set; }
        public string Solucion { get; set; }
        public string Enunciado { get; set; }
    
        public virtual ICollection<Alumno_Juego> Alumno_Juego { get; set; }
    }
}
