//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reto.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Matricula
    {
        public Matricula()
        {
            this.Notas = new HashSet<Notas>();
        }
    
        [Key]
        public int IdMatricula { get; set; }
        public Nullable<int> IdAlumno { get; set; }
        public Nullable<int> Grado { get; set; }
        public string Seccion { get; set; }
        public Nullable<int> IdNivelEscolar { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual NivelEscolar NivelEscolar { get; set; }
        public virtual ICollection<Notas> Notas { get; set; }
    }
}
