//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reto.Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Usuario
    {
        [Key]
        public string IdUsuario { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public string Clave { get; set; }
        public string Rol { get; set; }
        public Nullable<bool> FlagActivo { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
