//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno_Juego
    {
        public int IdAlumno { get; set; }
        public int IdJuego { get; set; }
        public Nullable<double> Calificacion { get; set; }
        public string Respuesta { get; set; }
        public Nullable<double> TiempoSegundos { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Juego Juego { get; set; }
    }
}
