//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriteriosEvaluacion
    {
        public CriteriosEvaluacion()
        {
            this.NotasCriterio = new HashSet<NotasCriterio>();
        }
    
        public int IdCriterio { get; set; }
        public Nullable<int> IdCurso { get; set; }
        public string Nombre { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual ICollection<NotasCriterio> NotasCriterio { get; set; }
    }
}
