//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.CriteriosEvaluacion = new HashSet<CriteriosEvaluacion>();
            this.DocenteCurso = new HashSet<DocenteCurso>();
        }
    
        public int IdCurso { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<CriteriosEvaluacion> CriteriosEvaluacion { get; set; }
        public virtual ICollection<DocenteCurso> DocenteCurso { get; set; }
    }
}
