//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasCriterio
    {
        public int IdMatricula { get; set; }
        public int IdDocenteCurso { get; set; }
        public int IdCriterio { get; set; }
        public int NroEvaluacion { get; set; }
        public Nullable<double> Nota { get; set; }
    
        public virtual CriteriosEvaluacion CriteriosEvaluacion { get; set; }
    }
}
