//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Alumno = new HashSet<Alumno>();
            this.Docente = new HashSet<Docente>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public string ApePaterno { get; set; }
        public string ApeMaterno { get; set; }
    
        public virtual ICollection<Alumno> Alumno { get; set; }
        public virtual ICollection<Docente> Docente { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
